server:
  port: 5123
  shutdown: graceful
  tomcat:
    accept-count: 100
    max-swallow-size: 50
    max-keep-alive-requests: 200
    threads:
      max: 500

spring:
  application:
    name: deviceet-device-management-service
  profiles:
    active: local # default profile

mongock:
  enabled: true
  migration-scan-package: deviceet.common.migration
  transactional: true
  lock-repository-name: mongock-lock
  migration-repository-name: mongock-migration