package deviceet.common.event;

public enum DomainEventType {
    EQUIPMENT_CREATED_EVENT,
    EQUIPMENT_DELETED_EVENT,
    EQUIPMENT_NAME_UPDATED_EVENT,
    DEVICE_CREATED_EVENT,
    DEVICE_NAME_CONFIGURED_EVENT,
}
